const KEY = "jhub_applykit_profile_v3";

const JOBS = Array.isArray(window.__JHUB_JOBS__) ? window.__JHUB_JOBS__ : [];

const el = (id) => document.getElementById(id);
const val = (x) => (x?.value ?? "").trim();

function splitLines(text) {
    return (text || "")
        .split("\n")
        .map(s => s.trim())
        .filter(Boolean);
}

function getJob(slug) {
    return JOBS.find(j => j.slug === slug) || null;
}

function loadProfile() {
    try {
        const raw = localStorage.getItem(KEY);
        if (!raw) return null;
        return JSON.parse(raw);
    } catch {
        return null;
    }
}

function saveProfile(profile) {
    localStorage.setItem(KEY, JSON.stringify(profile));
}

function buildResume(p) {
    const name = p.fullName || "Your Name";
    const head = p.headline ? `\n${p.headline}` : "";
    const contact = [p.email, p.phone, p.portfolio].filter(Boolean).join(" • ");

    const skillsArr = (p.skills || "")
        .split(",")
        .map(s => s.trim())
        .filter(Boolean);

    const exp = splitLines(p.experience);
    const edu = splitLines(p.education);
    const cert = splitLines(p.certs);

    const out = [];
    out.push(`${name}${head}`);
    if (contact) out.push(contact);
    out.push("");

    if (p.summary) {
        out.push("SUMMARY");
        out.push(p.summary);
        out.push("");
    }

    if (skillsArr.length) {
        out.push("SKILLS");
        out.push(skillsArr.join(", "));
        out.push("");
    }

    if (exp.length) {
        out.push("EXPERIENCE");
        exp.forEach(b => out.push(b.startsWith("-") ? b : `- ${b}`));
        out.push("");
    }

    if (edu.length) {
        out.push("EDUCATION");
        edu.forEach(b => out.push(b.startsWith("-") ? b : `- ${b}`));
        out.push("");
    }

    if (cert.length) {
        out.push("CERTIFICATIONS");
        cert.forEach(b => out.push(b.startsWith("-") ? b : `- ${b}`));
        out.push("");
    }

    return out.join("\n");
}

function buildCoverLetter(p, job) {
    const name = p.fullName || "Your Name";
    const roleLine = p.headline ? `(${p.headline})` : "";
    const skillsLine = p.skills
        ? p.skills.split(",").map(s => s.trim()).filter(Boolean).slice(0, 6).join(", ")
        : "";
    const summaryLine = p.summary ? p.summary.trim() : "";

    const dateStr = new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });

    return `${dateStr}

Hiring Manager
${job.company}

Dear Hiring Manager,

I’m writing to apply for the ${job.title} role at ${job.company}. I’m ${name} ${roleLine} and I can contribute immediately with strong delivery, clear communication, and attention to detail.

${summaryLine ? summaryLine + "\n\n" : ""}Key strengths I bring:
- Reliable execution and ownership
- Strong collaboration and stakeholder communication
${skillsLine ? `- Relevant skills: ${skillsLine}\n` : ""}

I would welcome the opportunity to discuss how I can support ${job.company}. I’ve included my resume for your review.

Sincerely,
${name}
${p.phone || ""}
${p.email || ""}
${p.portfolio || ""}`;
}

function buildMailto(job, cover) {
    const subject = `Application: ${job.title} — ${job.company}`;
    const body = `${cover}

---
NOTE: Please attach your resume file before sending.`;

    const params = new URLSearchParams();
    params.set("subject", subject);
    params.set("body", body);

    return `mailto:${job.applyEmail}?${params.toString()}`;
}

function escapeHtml(s) {
    return (s || "")
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;");
}

function exportPdf(profile, job, resume, cover) {
    const contact = [profile.email, profile.phone, profile.portfolio].filter(Boolean).join(" • ");

    const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Jhub Apply Kit</title>
<style>
  body{ font-family: Arial, sans-serif; margin: 18mm; color:#0f172a; }
  .top{ display:flex; justify-content:space-between; gap:16px; align-items:flex-start; }
  h1{ margin:0; font-size:20px; }
  .muted{ color:#64748b; font-size:12px; line-height:1.5; }
  .hr{ height:1px; background:#e2e8f0; margin:16px 0; }
  h2{ font-size:12px; margin:0 0 8px; letter-spacing:.08em; text-transform:uppercase; }
  .block{ font-size:12.5px; line-height:1.6; }
</style>
</head>
<body>
  <div class="top">
    <div>
      <h1>${escapeHtml(profile.fullName || "Your Name")} ${profile.headline ? `<span class="muted">${escapeHtml(profile.headline)}</span>` : ""}</h1>
      <div class="muted">${escapeHtml(contact)}</div>
    </div>
    <div class="muted" style="text-align:right;">
      <div><strong>${escapeHtml(job ? `${job.title} — ${job.company}` : "Application Pack")}</strong></div>
      <div>Generated by Jhub Apply Kit</div>
    </div>
  </div>

  <div class="hr"></div>

  <h2>Cover Letter</h2>
  <div class="block">${escapeHtml(cover).replaceAll("\n", "<br/>")}</div>

  <div class="hr"></div>

  <h2>Resume</h2>
  <div class="block">${escapeHtml(resume).replaceAll("\n", "<br/>")}</div>
</body>
</html>`;

    const w = window.open("", "_blank");
    if (!w) return { ok: false, msg: "Popup blocked. Allow popups and try again." };

    w.document.open();
    w.document.write(html);
    w.document.close();

    // ✅ No <script> tag inside strings; we print from the opener safely
    w.onload = () => {
        try {
            w.focus();
            setTimeout(() => w.print(), 250);
        } catch { }
    };

    return { ok: true, msg: "Opened print view." };
}

function init() {
    // Elements
    const fullName = el("fullName");
    const email = el("email");
    const phone = el("phone");
    const headline = el("headline");
    const portfolio = el("portfolio");
    const skills = el("skills");
    const summary = el("summary");
    const experience = el("experience");
    const education = el("education");
    const certs = el("certs");

    const saveProfileBtn = el("saveProfileBtn");
    const resetProfileBtn = el("resetProfileBtn");
    const profileHint = el("profileHint");

    const jobSelect = el("jobSelect");
    const jobMeta = el("jobMeta");

    const resumeText = el("resumeText");
    const coverLetter = el("coverLetter");

    const buildResumeBtn = el("buildResumeBtn");
    const copyResumeBtn = el("copyResumeBtn");
    const resumeHint = el("resumeHint");

    const generateCoverBtn = el("generateCoverBtn");
    const copyCoverBtn = el("copyCoverBtn");
    const openEmailBtn = el("openEmailBtn");
    const exportPdfBtn = el("exportPdfBtn");
    const coverHint = el("coverHint");

    if (!saveProfileBtn || !jobSelect) return;

    // Load profile
    const loaded = loadProfile();
    if (loaded) {
        if (fullName) fullName.value = loaded.fullName || "";
        if (email) email.value = loaded.email || "";
        if (phone) phone.value = loaded.phone || "";
        if (headline) headline.value = loaded.headline || "";
        if (portfolio) portfolio.value = loaded.portfolio || "";
        if (skills) skills.value = loaded.skills || "";
        if (summary) summary.value = loaded.summary || "";
        if (experience) experience.value = loaded.experience || "";
        if (education) education.value = loaded.education || "";
        if (certs) certs.value = loaded.certs || "";
        if (profileHint) profileHint.textContent = "Loaded ✅";
    }

    // URL job param
    const url = new URL(window.location.href);
    const preset = url.searchParams.get("job");
    if (preset && jobSelect) {
        jobSelect.value = preset;
    }

    function currentProfile() {
        return {
            fullName: val(fullName),
            email: val(email),
            phone: val(phone),
            headline: val(headline),
            portfolio: val(portfolio),
            skills: val(skills),
            summary: val(summary),
            experience: val(experience),
            education: val(education),
            certs: val(certs),
        };
    }

    function updateJobMeta(job) {
        if (!jobMeta) return;
        if (!job) {
            jobMeta.textContent = "No job selected.";
            return;
        }
        jobMeta.innerHTML = `
      <div style="display:grid; gap:6px;">
        <div><strong style="color:#0f172a">${job.title}</strong> at <strong style="color:#0f172a">${job.company}</strong></div>
        <div>${job.location} • ${job.workMode} • ${job.level}</div>
        <div>Deadline: ${job.deadline}</div>
        <div>Apply email: ${job.applyEmail}</div>
      </div>
    `;
    }

    // Initial meta update
    updateJobMeta(getJob(jobSelect.value));

    // Events
    saveProfileBtn.addEventListener("click", () => {
        const p = currentProfile();
        saveProfile(p);
        if (profileHint) profileHint.textContent = "Saved ✅";
        setTimeout(() => { if (profileHint) profileHint.textContent = "Tip: Save once, reuse across jobs."; }, 2200);
    });

    resetProfileBtn?.addEventListener("click", () => {
        localStorage.removeItem(KEY);
        [fullName, email, phone, headline, portfolio, skills, summary, experience, education, certs].forEach(x => { if (x) x.value = ""; });
        if (profileHint) profileHint.textContent = "Reset ✅";
        setTimeout(() => { if (profileHint) profileHint.textContent = "Tip: Save once, reuse across jobs."; }, 2200);
    });

    jobSelect.addEventListener("change", () => {
        updateJobMeta(getJob(jobSelect.value));
    });

    buildResumeBtn?.addEventListener("click", () => {
        const p = currentProfile();
        saveProfile(p);
        const r = buildResume(p);
        if (resumeText) resumeText.value = r;
        if (resumeHint) resumeHint.textContent = "Built ✅";
        setTimeout(() => { if (resumeHint) resumeHint.textContent = "Build creates a structured resume you can edit."; }, 2200);
    });

    copyResumeBtn?.addEventListener("click", async () => {
        try {
            await navigator.clipboard.writeText(resumeText?.value || "");
            if (resumeHint) resumeHint.textContent = "Copied ✅";
        } catch {
            if (resumeHint) resumeHint.textContent = "Copy failed.";
        }
        setTimeout(() => { if (resumeHint) resumeHint.textContent = "Build creates a structured resume you can edit."; }, 2200);
    });

    generateCoverBtn?.addEventListener("click", () => {
        const job = getJob(jobSelect.value);
        if (!job) {
            if (coverHint) coverHint.textContent = "Select a job first.";
            setTimeout(() => { if (coverHint) coverHint.textContent = "Export PDF opens print view → Save as PDF."; }, 2200);
            return;
        }
        const p = currentProfile();
        saveProfile(p);
        const c = buildCoverLetter(p, job);
        if (coverLetter) coverLetter.value = c;
        if (coverHint) coverHint.textContent = "Generated ✅";
        setTimeout(() => { if (coverHint) coverHint.textContent = "Export PDF opens print view → Save as PDF."; }, 2200);
    });

    copyCoverBtn?.addEventListener("click", async () => {
        try {
            await navigator.clipboard.writeText(coverLetter?.value || "");
            if (coverHint) coverHint.textContent = "Copied ✅";
        } catch {
            if (coverHint) coverHint.textContent = "Copy failed.";
        }
        setTimeout(() => { if (coverHint) coverHint.textContent = "Export PDF opens print view → Save as PDF."; }, 2200);
    });

    openEmailBtn?.addEventListener("click", () => {
        const job = getJob(jobSelect.value);
        if (!job) {
            if (coverHint) coverHint.textContent = "Select a job first.";
            setTimeout(() => { if (coverHint) coverHint.textContent = "Export PDF opens print view → Save as PDF."; }, 2200);
            return;
        }
        const p = currentProfile();
        saveProfile(p);
        const cover = (coverLetter?.value || "").trim() || buildCoverLetter(p, job);
        if (coverLetter) coverLetter.value = cover;
        window.location.href = buildMailto(job, cover);
    });

    exportPdfBtn?.addEventListener("click", () => {
        const job = getJob(jobSelect.value);
        if (!job) {
            if (coverHint) coverHint.textContent = "Select a job first (PDF includes job header).";
            setTimeout(() => { if (coverHint) coverHint.textContent = "Export PDF opens print view → Save as PDF."; }, 2400);
            return;
        }

        const p = currentProfile();
        saveProfile(p);

        const resume = (resumeText?.value || "").trim() || buildResume(p);
        if (resumeText) resumeText.value = resume;

        const cover = (coverLetter?.value || "").trim() || buildCoverLetter(p, job);
        if (coverLetter) coverLetter.value = cover;

        const res = exportPdf(p, job, resume, cover);
        if (coverHint) coverHint.textContent = res.ok ? "Opened print view ✅" : res.msg;
        setTimeout(() => { if (coverHint) coverHint.textContent = "Export PDF opens print view → Save as PDF."; }, 2600);
    });
}

document.addEventListener("DOMContentLoaded", init);
